### ISSUE TITLE
issue in user authentication while login

### ISSUE THREAD

**Issue by rinjumanandhar** [nodebeats/mern-bitsbeat#3]
@RajShresthas   #JsonWebTokenError: jwt malformed is obtained while passing jwt in header while performing logout operation

@RajShresthas   #When login is suspended after entering  wrong password 3 times, then server connection is lost

![error](https://user-images.githubusercontent.com/44392335/49509104-8a1cb280-f8ac-11e8-8596-a5d0cf68b307.png)

**Comment by RajShresthas** [comment]
#JWTTokenError is resolved.

**Comment by rinjumanandhar** [comment]
JwtToken error resolved tested
Server connection lost error resolved tested
